version : "3"
services:
    nodejsd:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - PORT=3000

    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=timmy
            - MONGO_INITDB_ROOT_PASSWORD=password
    redis:
        image: redis